version: "3"
services:
  #container
  api:
    #name of the container
    build: .
    depends_on:
      - postgres #start the postgres container first
    ports:
      - 8000:8000 #<port on localhost>:<port on container>
    volumes:
      #binding for syncing
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      #environment variables
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=mypass
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  postgres:
    #to run postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=fastapi
    volumes:
      #storing
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
