"""add phone number

Revision ID: ac39a0703eeb
Revises: 506f528144b4
Create Date: 2022-10-20 13:05:04.227123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac39a0703eeb'
down_revision = '506f528144b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'phone_number')
    # ### end Alembic commands ###
