name: Build and Deploy Code #just a name

on: [push, pull_request] #activates on this condition (push or pull on any branch)
  # push:
  #   branches: ["main"]

jobs:  #set of steps that execute on the same runner
  job1: #name
    runs-on: ubuntu latest #defines which runner it will use
    steps:
      - name: pulling git repo #name of the action
        uses: actions/checkout@v3 #actual command for the action
      - name: Install python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirement.txt