name: Build and Deploy Code #just a name

on: [push, pull_request] #activates on this condition (push or pull on any branch)
  # push:
  #   branches: ["main"]

jobs:  #set of steps that execute on the same runner
  job1: #name
    env: 
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5434
      DATABASE_PASSWORD: mypass
      DATABASE_NAME: fastapi 
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60


    runs-on: ubuntu-latest #defines which runner it will use
    steps:
      - name: pulling git repo #name of the action
        uses: actions/checkout@v3 #actual command for the action
      - name: Install python 
        uses: actions/setup-python@v4 #setting up python
        with:
          python-version: '3.10'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
        run: |
          pip install pytest
          pytest